import { readFile, writeFile, mkdir, cp, readdir, rm } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { services, menus } from './content.mjs';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(await readFile(join(root, 'site.config.json'), 'utf8'));
const origin = new URL(process.env.SITE_URL || config.siteUrl);
if (origin.protocol !== 'https:' || origin.pathname !== '/' || origin.search || origin.hash) throw new Error('SITE_URL must be an HTTPS origin without a path.');
const site = origin.origin;
const verify = process.env.NAVER_SITE_VERIFICATION || config.naverVerification;
const rootMode = process.argv.includes('--root');
const out = rootMode ? root : join(root, 'dist');
if (!rootMode) { await rm(out, {recursive: true, force: true}); await mkdir(out, {recursive: true}); await cp(join(root,'assets'),join(out,'assets'),{recursive:true}); }
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const abs = path => site + path;
const phone = config.telephone;
const dial = phone.replaceAll('-', '');
const img = (name, alt, extra='') => `<picture><source srcset="/assets/images/${name}.webp" type="image/webp"><img src="/assets/images/${name}.jpg" alt="${esc(alt)}" width="${name.includes('hero') ? 1536 : 1254}" height="${name.includes('hero') ? 1024 : 1254}" decoding="async" ${extra}></picture>`;
const brandEntity = {
  '@type': 'BeautySalon', '@id': abs('/#business'), name: config.brand,
  url: abs('/'), telephone: phone, image: abs('/assets/images/suwon-brow-studio-interior.jpg'),
  areaServed: {'@type':'City',name:'수원시'},
  description: '수원역 인근에서 눈썹 결과 얼굴 비율을 함께 살피는 눈썹 디자인 상담.'
};
const list = {'@context':'https://schema.org','@type':'ItemList','@id':abs('/#brow-collection'),name:'결담 브로우 수원눈썹문신 디자인 프로그램',numberOfItems:services.length,itemListOrder:'https://schema.org/ItemListOrderAscending',itemListElement:services.map((s,i)=>({'@type':'ListItem',position:i+1,name:s.name,image:abs(`/assets/images/${s.image}.jpg`),url:abs(`/services/${s.slug}/`)}))};
function header(path){return `<a class="skip-link" href="#main">본문으로 이동</a><header class="header"><div class="wrap header-inner"><a class="wordmark" href="/" aria-label="결담 브로우 홈"><strong>GYEOLDAM</strong><small>결담 브로우 · SUWON</small></a><nav class="nav" id="main-nav" aria-label="주요 메뉴">${menus.map(m=>`<a href="${m.path}"${path===m.path?' aria-current="page"':''}>${m.label}</a>`).join('')}</nav><a class="header-call" href="tel:${dial}">상담 ${phone}</a><button type="button" class="menu-toggle" aria-controls="main-nav" aria-expanded="false">메뉴</button></div></header>`}
function footer(){return `<footer class="footer"><div class="wrap"><div class="footer-inner"><div><a class="footer-brand" href="/">GYEOLDAM BROW</a><p>결담 브로우 · 경기도 수원시, 수원역 인근<br>상담 전화 <a href="tel:${dial}">${phone}</a></p></div><nav class="footer-links" aria-label="하단 메뉴">${menus.map(m=>`<a href="${m.path}">${m.label}</a>`).join('')}</nav></div><div class="copyright">© ${new Date().getUTCFullYear()} GYEOLDAM BROW. All rights reserved.</div></div></footer><a class="mobile-call" href="tel:${dial}"><span>결담 브로우 상담</span><strong>${phone}</strong></a>`}
function contactBand(){return `<section class="contact-band"><div class="wrap contact-inner"><div><p class="eyebrow">A BROW THAT FEELS LIKE YOU</p><h2>어울리는 눈썹의 시작은,<br>충분한 대화입니다.</h2><p>수원역 인근 · 원하는 디자인과 방문 일정을 먼저 상담해주세요.</p></div><div class="contact-actions"><a class="contact-number" href="tel:${dial}">${phone}</a><br><a class="button light" href="/contact/">상담·방문 안내</a></div></div></section>`}
const faqHTML = entries => `<div class="faq">${entries.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`;
function card(s,i,short=false){return `<article class="design-card"><a class="card-image" href="/services/${s.slug}/" aria-label="${s.name} 상세 안내">${img(s.image,`${s.name} 눈썹 디자인 예시`,'loading="lazy"')}<span class="card-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span></a><h3><a href="/services/${s.slug}/">${s.name}</a></h3><p class="card-en">${s.english}</p>${short?'':`<p class="card-desc">${s.summary}</p>`}<a class="card-link" href="/services/${s.slug}/">디자인 알아보기</a></article>`}
const mainFAQ = [['어떤 눈썹 디자인이 저에게 어울릴까요?', '얼굴 비율, 기존 모량과 눈썹의 방향, 평소 메이크업 취향을 함께 살펴봅니다. 원하는 이미지와 피하고 싶은 인상을 알려주시면 상담에 도움이 됩니다.'],['기존 눈썹문신이 있어도 상담할 수 있나요?', '가능합니다. 이전 작업 시기와 현재 눈썹 사진을 준비해주세요. 남은 색과 형태를 확인한 뒤 디자인 가능 범위를 안내합니다.'],['비용과 일정은 어떻게 확인하나요?', '원하는 디자인과 기존 눈썹 상태에 따라 상담이 필요합니다. 전화로 방문 가능 일정과 상담 범위를 먼저 문의해주세요.'],['수원역에서 방문하려면 어떻게 해야 하나요?', '결담 브로우는 수원역 인근을 기준으로 상담을 안내합니다. 방문 전 전화로 상세 위치와 약속된 일정을 확인해주세요.']];
function shell({path,title,description,image,body,breadcrumb=[],isHome=false,noindex=false}){
 const graph = [brandEntity,{'@type':'WebSite','@id':abs('/#website'),url:abs('/'),name:config.brand,inLanguage:'ko-KR',publisher:{'@id':abs('/#business')}},{'@type':'WebPage','@id':abs(path+'#webpage'),url:abs(path),name:title,description,inLanguage:'ko-KR',isPartOf:{'@id':abs('/#website')},primaryImageOfPage:{'@type':'ImageObject',url:abs(`/assets/images/${image}.jpg`)},...(isHome?{mainEntity:{'@id':abs('/#brow-collection')}}:{})}];
 if(breadcrumb.length)graph.push({'@type':'BreadcrumbList',itemListElement:[{name:'결담 브로우',path:'/'},...breadcrumb].map((b,i)=>({'@type':'ListItem',position:i+1,item:{'@id':abs(b.path),name:b.name}}))});
 return `<!doctype html>\n<html lang="ko">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>${esc(title)}</title>\n<meta name="description" content="${esc(description)}">\n<meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}">\n<link rel="canonical" href="${abs(path)}">\n${verify?`<meta name="naver-site-verification" content="${esc(verify)}">`:'<!-- NAVER_SITE_VERIFICATION: add the issued code to site.config.json or the Cloudflare build environment. -->'}\n<meta property="og:type" content="website">\n<meta property="og:locale" content="ko_KR">\n<meta property="og:site_name" content="${esc(config.brand)}">\n<meta property="og:title" content="${esc(title)}">\n<meta property="og:description" content="${esc(description)}">\n<meta property="og:url" content="${abs(path)}">\n<meta property="og:image" content="${abs(`/assets/images/${image}.jpg`)}">\n<meta name="theme-color" content="#30231f">\n<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">\n<link rel="stylesheet" href="/assets/site.css">\n<script defer src="/assets/site.js"></script>\n<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph},null,2).replaceAll('<','\\u003c')}</script>\n${isHome?`<script type="application/ld+json">${JSON.stringify(list,null,2)}</script>`:''}\n</head>\n<body>\n${header(path)}\n<main id="main">${body}</main>\n${footer()}\n</body>\n</html>\n`;
}
const principle = `<div class="principle-grid"><article><span class="num">01</span><h3>얼굴의 비율부터</h3><p>눈매와 골격, 표정을 함께 살펴 어울리는 굵기와 길이를 찾습니다.</p></article><article><span class="num">02</span><h3>본래의 결을 존중</h3><p>기존 모의 흐름과 빈 부분을 확인하고 필요한 표현을 조율합니다.</p></article><article><span class="num">03</span><h3>충분한 디자인 상담</h3><p>원하는 인상과 피하고 싶은 형태를 함께 확인한 뒤 방향을 정합니다.</p></article></div>`;
const steps = `<ol class="steps"><li><span class="num">01</span><div><h3>현재 눈썹과 취향 확인</h3><p>기존 눈썹 상태와 평소 메이크업을 함께 살펴봅니다.</p></div></li><li><span class="num">02</span><div><h3>얼굴에 맞는 디자인 조율</h3><p>형태, 굵기, 길이와 원하는 선명도를 비교합니다.</p></div></li><li><span class="num">03</span><div><h3>진행 범위와 일정 상담</h3><p>가능한 범위와 방문 일정, 이후 안내를 확인합니다.</p></div></li></ol>`;
const homeBody = `<section class="hero"><div class="hero-copy fade-in"><p class="eyebrow">GYEOLDAM BROW · SUWON</p><h1>수원눈썹문신,<span>나에게 어울리는<br><em>결을 찾다.</em></span></h1><p class="hero-desc">유행하는 모양보다, 당신의 얼굴에 편안한 눈썹.<br>결담은 본래의 결에서 디자인을 시작합니다.</p><div class="hero-actions"><a class="button light" href="/design/">눈썹 디자인 보기</a><a class="button outline" href="tel:${dial}">전화 상담</a></div><p class="hero-note">수원역 인근 · 1:1 디자인 상담</p></div><div class="hero-visual">${img('suwon-gyeoldam-brow-hero','자연스러운 눈썹을 표현한 결담 브로우 브랜드 이미지','fetchpriority="high"')}<span class="image-caption">THE BEAUTY OF YOUR OWN BROW</span></div></section><section class="collection" id="brow-collection" data-carousel aria-labelledby="collection-title"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">BROW COLLECTION</p><h2 id="collection-title">당신에게 맞는 눈썹 디자인</h2></div><p>결부터 음영까지, 여섯 가지 디자인 안내를 살펴보세요.</p><div class="carousel-controls"><button type="button" data-prev aria-label="이전 디자인">‹</button><button type="button" data-next aria-label="다음 디자인">›</button></div></div><div class="carousel-track" tabindex="0" aria-label="여섯 가지 눈썹 디자인 카드">${services.map((s,i)=>card(s,i)).join('')}</div></div></section><section class="section"><div class="wrap"><div class="philosophy"><div class="philosophy-visual">${img('suwon-brow-studio-interior','결담 브로우가 지향하는 편안한 상담 공간 이미지','loading="lazy"')}<p class="photo-label">결담이 지향하는 공간의 분위기</p></div><div><p class="eyebrow">OUR PHILOSOPHY</p><h2>조금 더 또렷하게,<br><span>여전히 나답게.</span></h2><p>눈썹은 얼굴의 작은 부분이지만 인상을 바꾸는 섬세한 선입니다. 결담 브로우는 얼굴 비율과 현재 눈썹, 일상의 메이크업 취향을 함께 살핍니다.</p><p style="margin-top:15px">자연눈썹부터 부드러운 음영, 남자눈썹과 잔흔 상담까지. 정해진 모양을 고르기보다 본인에게 어울리는 방향을 함께 찾아갑니다.</p><a class="text-link" href="/brand/">결담의 디자인 기준</a></div></div>${principle}</div></section><section class="section band"><div class="wrap journey"><div><p class="eyebrow">A PERSONAL DESIGN</p><h2>처음 만나는 순간부터,<br>차분하고 충분하게.</h2>${steps}<a class="text-link" href="/guide/">상담 전 이용 가이드</a></div><div>${img('suwon-brow-design-consultation','거울과 디자인 펜슬을 사용한 눈썹 상담 이미지','loading="lazy"')}<p class="photo-label">개인의 눈썹 상태와 취향을 살피는 디자인 상담</p></div></div></section><section class="section"><div class="wrap faq-wrap"><div class="faq-heading"><p class="eyebrow">QUESTIONS & ANSWERS</p><h2>상담 전에 궁금한 것들</h2></div>${faqHTML(mainFAQ)}</div></section>${contactBand()}`;
const pages = [{path:'/',title:'수원눈썹문신 결담 브로우 | 수원역 눈썹 디자인',description:'수원역 인근 결담 브로우. 자연눈썹·콤보눈썹·남자눈썹·파우더눈썹과 리터치·잔흔 상담을 안내합니다. 얼굴 비율과 본래의 결을 살피는 눈썹 디자인, 전화 010-8142-1319.',image:'suwon-gyeoldam-brow-hero',body:homeBody,isHome:true}];
function pageHero(m){return `<div class="wrap"><nav class="breadcrumb" aria-label="현재 위치"><a href="/">결담 브로우</a><span aria-hidden="true">/</span><span>${m.label}</span></nav><section class="page-hero"><div><p class="eyebrow">${m.english}</p><h1>${m.lead}</h1><p>${m.description}</p><a class="button" href="tel:${dial}">전화로 상담하기</a></div><div class="image-wrap">${img(m.image,m.imageAlt,'fetchpriority="high"')}<p class="photo-label">${m.imageLabel}</p></div></section></div>`}
for(const m of menus){
 let inner='';
 if(m.path==='/brand/')inner=`<section class="section"><div class="wrap"><div class="philosophy"><div><p class="eyebrow">THE GYEOLDAM STANDARD</p><h2>나의 눈썹에서 시작하는<br>나의 디자인.</h2><p>결담 브로우는 수원역 인근에서 자연스러운 눈썹 인상을 상담하는 뷰티샵입니다. 눈썹을 하나의 유행으로 정하기보다, 본래 모양과 얼굴의 비율을 먼저 살피는 방향을 지향합니다.</p></div><div><p>원하는 이미지가 뚜렷하지 않아도 괜찮습니다. 평소 메이크업 사진, 마음에 드는 분위기, 피하고 싶은 모양을 함께 비교하면서 디자인의 기준을 찾을 수 있습니다.</p><p style="margin-top:15px">기존 눈썹문신이 있다면 남은 색과 형태를 먼저 확인합니다. 현재 상태에서 가능한 범위를 안내하고, 무리한 변화를 권하기보다 충분히 이해한 뒤 선택할 수 있도록 상담합니다.</p></div></div>${principle}</div></section>`;
 if(m.path==='/design/')inner=`<section class="section"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">FIND YOUR BROW</p><h2>여섯 가지 디자인 안내</h2></div><p>원하는 분위기를 고르고, 상세 안내에서 기준을 확인해보세요.</p></div><div class="service-grid">${services.map((s,i)=>card(s,i)).join('')}</div><div class="notice">디자인의 적합성과 진행 범위는 현재 눈썹과 피부 상태에 따라 달라집니다. 비용·방문 일정·리터치 조건은 상담 시 안내합니다.</div></div></section>`;
 if(m.path==='/gallery/')inner=`<section class="section"><div class="wrap"><p class="gallery-intro">AI로 제작한 디자인 예시이며, 실제 고객의 시술 전후 사진은 아닙니다. 원하는 분위기를 상담할 때 참고할 수 있고, 각 이미지를 선택하면 해당 디자인의 특징과 상담 기준을 확인할 수 있습니다.</p><div class="gallery-grid">${services.map(s=>`<figure><a href="/services/${s.slug}/">${img(s.image,`${s.name} 분위기의 눈썹 디자인 예시`,'loading="lazy"')}<figcaption>${s.name}<small>${s.english}</small></figcaption></a></figure>`).join('')}</div></div></section>`;
 if(m.path==='/guide/')inner=`<div class="wrap article-layout"><div class="article-content"><section class="article-section"><h2>상담 전에 준비하면 좋은 것</h2><p>현재 눈썹이 보이는 사진과 평소 메이크업 사진을 준비하면 원하는 분위기를 함께 이해하는 데 도움이 됩니다. 기존 눈썹문신이 있다면 이전 작업 시기와 보완 이력을 알려주세요.</p><ul class="check-list"><li>현재 눈썹이 잘 보이는 정면 사진</li><li>원하는 분위기 또는 피하고 싶은 형태</li><li>이전 눈썹 작업 시기와 잔흔 유무</li><li>중요한 일정과 방문 가능한 날짜</li></ul></section><section class="article-section"><h2>디자인 상담의 흐름</h2>${steps}</section><section class="article-section"><h2>진행과 회복 경과를 함께 확인합니다</h2><p>초기 색과 회복 뒤 인상에는 차이가 있을 수 있고, 피부 상태에 따라 경과도 다르게 나타납니다. 구체적인 관리 방법은 진행 내용에 맞춰 안내받아야 합니다. 회복 중 변화나 불편함이 있다면 상태를 확인할 수 있도록 문의해주세요.</p><div class="notice">피부 자극이나 기존 잔흔, 최근의 관련 작업이 있다면 상담 전에 알려주세요. 현재 상태에서 적합한 진행인지 확인하는 것이 우선입니다.</div></section><section class="article-section"><h2>자주 묻는 질문</h2>${faqHTML(mainFAQ)}</section></div>${aside()}</div>`;
 if(m.path==='/contact/')inner=`<section class="section"><div class="wrap location-panel"><div><p class="eyebrow">CONTACT & LOCATION</p><h2>수원역 인근 결담 브로우</h2><p>원하는 디자인, 현재 눈썹 상태와 방문 가능한 일정을 알려주세요. 처음 방문하시는 분은 전화로 상세 위치와 일정을 안내받으실 수 있습니다.</p><dl><div><dt>상담 전화</dt><dd><a href="tel:${dial}">${phone}</a></dd></div><div><dt>위치 안내</dt><dd>경기도 수원시 · 수원역 인근</dd></div><div><dt>방문 안내</dt><dd>방문 전 전화 상담 후 일정 조율</dd></div><div><dt>상담 내용</dt><dd>눈썹 디자인 · 기존 잔흔 · 리터치</dd></div></dl><a class="button" href="tel:${dial}">전화 상담하기</a></div><div class="location-box"><p class="eyebrow">NEAR SUWON STATION</p><p class="display">Suwon,<br>your next brow.</p><p>수원역 주변 지도를 확인하고,<br>방문할 상세 위치는 상담 시 안내받으세요.</p><a class="button outline" href="https://map.naver.com/p/search/%EC%88%98%EC%9B%90%EC%97%AD" target="_blank" rel="noopener noreferrer">네이버 지도에서 수원역 보기</a><div class="notice">지도 링크는 수원역 위치를 보여줍니다. 매장까지의 이동 경로와 방문 주소는 전화로 안내합니다.</div></div></div></section>`;
 pages.push({...m,body:pageHero(m)+inner+contactBand(),breadcrumb:[{name:m.label,path:m.path}]});
}
function aside(){return `<aside class="info-card"><p class="eyebrow">GYEOLDAM BROW</p><h2>나에게 맞는 디자인 상담</h2><p>현재 눈썹과 원하는 분위기를 함께 살펴보세요.<br>수원역 인근 · 방문 전 일정 상담</p><a class="phone" href="tel:${dial}">${phone}</a><a class="button" href="tel:${dial}">전화 상담</a><a class="text-link" href="/contact/">상담·오시는 길</a></aside>`}
for(const s of services){
 const path=`/services/${s.slug}/`;
 const hero=`<div class="wrap"><nav class="breadcrumb" aria-label="현재 위치"><a href="/">결담 브로우</a><span>/</span><a href="/design/">눈썹 디자인</a><span>/</span><span>${s.name}</span></nav><section class="page-hero"><div><p class="eyebrow">${s.english}</p><h1>${s.name}<br>${s.lead}</h1><p>${s.summary}</p><a class="button" href="tel:${dial}">${s.name} 상담하기</a></div><div class="image-wrap">${img(s.image,`${s.name} 눈썹 디자인 예시`,'fetchpriority="high"')}<p class="photo-label">${s.name} 디자인 예시</p></div></section></div>`;
 const body=hero+`<div class="wrap article-layout"><div class="article-content"><section class="article-section"><h2>${s.name} 디자인의 기준</h2><p>${s.body}</p></section><section class="article-section"><h2>이런 고민이라면 함께 살펴보세요</h2><ul class="check-list">${s.suitable.map(t=>`<li>${t}</li>`).join('')}</ul></section><section class="article-section"><h2>상담에서 확인하는 세 가지</h2>${s.points.map(([h,p])=>`<h3>${h}</h3><p>${p}</p>`).join('')}</section><section class="article-section"><h2>상담 전 준비사항</h2><p>현재 눈썹이 잘 보이는 사진, 이전 작업 시기, 평소 메이크업 사진을 준비해주세요. 원하는 분위기와 피하고 싶은 인상을 알려주시면 상담 방향을 함께 정하는 데 도움이 됩니다.</p><div class="notice">디자인 적합성, 진행 범위와 일정은 현재 상태를 확인한 뒤 안내합니다. 회복 경과와 표현에는 개인차가 있습니다.</div></section><section class="article-section"><h2>${s.name} 자주 묻는 질문</h2>${faqHTML(s.faq)}</section></div>${aside()}</div><section class="section related"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">EXPLORE THE COLLECTION</p><h2>다른 디자인도 살펴보세요</h2></div><a class="text-link" href="/design/">전체 디자인 보기</a></div><div class="service-grid">${services.filter(x=>x!==s).slice(0,3).map((x,i)=>card(x,i)).join('')}</div></div></section>`+contactBand();
 pages.push({path,title:`${s.name} 안내 | 수원눈썹문신 결담 브로우`,description:s.description,image:s.image,body,breadcrumb:[{name:'눈썹 디자인',path:'/design/'},{name:s.name,path}]});
}
for(const p of pages){const file=join(out,p.path,'index.html');await mkdir(dirname(file),{recursive:true});await writeFile(file,shell(p));}
await writeFile(join(out,'404.html'),shell({path:'/404.html',title:'페이지를 찾을 수 없습니다 | 결담 브로우',description:'결담 브로우의 홈 또는 눈썹 디자인 안내로 이동해주세요.',image:'suwon-gyeoldam-brow-hero',noindex:true,body:'<section class="error-page"><p class="display">404</p><h1>페이지를 찾을 수 없습니다.</h1><p>홈이나 눈썹 디자인 안내에서 다시 찾아보세요.</p><a class="button" href="/">결담 브로우 홈</a></section>'}));
const xml = s => esc(s).replaceAll("'",'&apos;');
await writeFile(join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p=>`  <url><loc>${xml(abs(p.path))}</loc></url>`).join('\n')}\n</urlset>\n`);
await writeFile(join(out,'robots.txt'),`User-agent: *\nAllow: /\n\nSitemap: ${abs('/sitemap.xml')}\n`);
const pubDate='Wed, 07 Oct 2026 11:30:00 GMT';
const rssEntries=pages.filter(p=>p.path!=='/').map(p=>`<item><title>${xml(p.title)}</title><link>${xml(abs(p.path))}</link><guid isPermaLink="true">${xml(abs(p.path))}</guid><pubDate>${pubDate}</pubDate><description><![CDATA[${p.body.replaceAll(']]>',']]]]><![CDATA[>')}]]></description></item>`).join('\n');
await writeFile(join(out,'rss.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel><title>결담 브로우 디자인·이용 안내</title><link>${xml(abs('/'))}</link><description>수원역 인근 결담 브로우의 눈썹 디자인과 상담 안내</description><language>ko-KR</language>\n${rssEntries}\n</channel></rss>\n`);
await writeFile(join(out,'_headers'),`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n\n/assets/*\n  Cache-Control: public, max-age=86400\n\n/robots.txt\n  Content-Type: text/plain; charset=utf-8\n\n/sitemap.xml\n  Content-Type: application/xml; charset=utf-8\n\n/rss.xml\n  Content-Type: application/rss+xml; charset=utf-8\n`);
await writeFile(join(out,'_redirects'),`/index.html / 301\n${pages.filter(p=>p.path!=='/').map(p=>`${p.path}index.html ${p.path} 301`).join('\n')}\n`);
// Preserve the exact ownership HTML supplied by Naver; never synthesize a verification token.
for(const f of await readdir(root)){if(/^naver[a-zA-Z0-9]+\.html$/.test(f)&&!rootMode)await cp(join(root,f),join(out,f));}
await writeFile(join(root,'NAVER-URLS.txt'),pages.map(p=>abs(p.path)).join('\n')+'\n\n사이트맵: '+abs('/sitemap.xml')+'\nRSS: '+abs('/rss.xml')+'\n');
console.log(`Generated ${pages.length} indexable pages + 404, sitemap, RSS, robots at ${out}. SEO origin: ${site}. Naver verification: ${verify?'configured':'not yet issued'}.`);
